// Copies the compiled ABI into @lootvault/shared as a typed `as const` export.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const artifactUrl = new URL("../artifacts/contracts/LootVault1155.sol/LootVault1155.json", import.meta.url);
const outPath = fileURLToPath(new URL("../../shared/src/abi/lootVault1155.ts", import.meta.url));

const { abi } = JSON.parse(readFileSync(artifactUrl, "utf8"));
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// AUTO-GENERATED by packages/contracts/scripts/export-abi.mjs. Do not edit.\n` +
    `export const lootVault1155Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
);
console.log(`Wrote ${abi.length} ABI entries to ${outPath}`);
